GeneralArguments:
  # exp_name: "{date.today().strftime('%d_%m')}"
  exp_name: "test_code_refactor"
  dataset: "CDRP-bio"
  flow: "eval" # "data", "train", "eval"
  debug_mode: false
  seed: 42
  gpus: 1
  base_dir: "/Users/alonshp/rosetta-data"
  overwrite_experiment: false
  run_parallel: false
  slice_id: null
  run_all_datasets: false

DataArguments:
  use_cache: true # "Use cache if true."
  modality: "CellPainting"
  #   description: "Modality name."
  # modality_str: "cp"
  #   description: "Modality string."
  profile_type: "augmented" # "normalized", "augmented", "normalized_variable_selected"
  #   description: "Profile type."
  test_split_ratio: 0.5 # "Ratio for test data split."
  val_split_ratio: 0.1 # "Validation data split ratio."
  normalize_condition: "train" # "Normalization condition: train, DMSO, or all data."
  plate_normalized: true # "Normalize by plate if true."
  norm_method: "standardize" # "Normalization method."
  feature_select: true # "Run feature selection or use predefined features."
  corr_threshold: 0.9 # "Correlation threshold for feature selection."
  n_samples_for_training: null # "Number of training samples to use (all if null)."
  var_threshold: 0.0001 # "Variance threshold for feature selection."
    
ModelArguments:
  lr: 0.005 # "Learning rate."
  dropout: 0.0 # "Dropout rate."
  latent_dim: 16 # "Size of latent dimension."
  l2_lambda: 0.007 # "L2 regularization lambda."
  l1_latent_lambda: 0 # "L1 regularization lambda for latent dimension."
  batch_size: 32 # "Batch size."
  max_epochs: 500 # "Maximum number of epochs."
  # use_16bit: false # "Use 16-bit precision for training."
  save_top_k: 1 # "Save top K checkpoints."
  tune_hyperparams: false # "Tune hyperparameters."
  n_tuning_trials: 150 # "Number of tuning trials."
  deep_decoder: false # "Use deep decoder if true."
  encoder_type: "default" # "Encoder type (default, shallow, deep)."
  max_epochs_in_trial: 100 # "Maximum epochs per trial."


EvalArguments:
  with_l1k: true # "Calculate L1K metrics."
  num_simulations: 1000 # "Number of simulations."
  do_baseline: true # "Run baseline evaluation."
  do_original: false # "Run original evaluation."
  by_dose: false # "Run by dose."
  z_trim: null # "Z-score threshold for trimming."
  normalize_by_all: true # "Normalize using all data including treatment."
  run_dose_if_exists: false # "Run dose if exists."
  filter_by_highest_dose: true # "Run only highest dose."
  latent_exp: false # "Run latent dimension experiment."
  load_corr_if_exists: true # "Load correlation if exists."
  min_max_norm: false # "Apply Min-Max normalization."
  rand_reps: 5 # "Number of random sampling repetitions."
  filter_non_reproducible: true # "Filter non-reproducible compounds for SHAP evaluation."
  run_shap: true # "Run SHAP evaluation."


MoaArguments:
  tune: false # "Tune hyperparameters."
  tune_first_fold: false # "Tune only for the first fold."
  filter_perts: "HighRepUnion" # "Filter perturbations (e.g., HighRepUnion, onlyCP)."
  n_exps: 1 # "Number of experiments."
  do_fusion: true # "Run fusion if true."
  folds: 10 # "Number of folds for cross-validation."
  min_samples: 4 # "Minimum samples per perturbation."
  exp_seed: 42 # "Experiment seed."
  rep_corr_fileName: "RepCorrDF" # "Replicate correlation file name."
  do_all_filter_groups: false # "Run all filter groups."
  moa_dirname: "MoAprediction" # "MOA directory name."
  with_l1k: true # "Run L1K analysis."
  moa_plate_normalized: true # "Normalize by plate in MOA analysis."

