GeneralArguments:
  exp_name: "test_exp"
  dataset: "CDRP-bio"
  debug_mode: false
  seed: 42

DataArguments:
  profile_type: "augmented"
  modality: "CellPainting"

ModelArguments:
  tune_hyperparams: false
  deep_decoder: false
  encoder_type: "shallow"